// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package DB

import (
	"database/sql"
)

type Address struct {
	Country string `json:"country"`
	City    string `json:"city"`
	Street  string `json:"street"`
}

type Course struct {
	CID         int64  `json:"c_id"`
	CourseName  string `json:"course_name"`
	Semester    string `json:"semester"`
	Description string `json:"description"`
	UID         int64  `json:"u_id"`
}

type Event struct {
	EID       int64  `json:"e_id"`
	CID       int64  `json:"c_id"`
	StartTime string `json:"start_time"`
	EndTime   string `json:"end_time"`
	Title     string `json:"title"`
	Color     string `json:"color"`
}

type Mentor struct {
	MID             int64  `json:"m_id"`
	CID             int64  `json:"c_id"`
	Username        string `json:"username"`
	FullName        string `json:"full_name"`
	HashedPassword  string `json:"hashed_password"`
	Email           string `json:"email"`
	Description     string `json:"description"`
	EvaluationCount int32  `json:"evaluation_count"`
	Score           int32  `json:"score"`
	Balance         int32  `json:"balance"`
	UID             int64  `json:"u_id"`
	Country         string `json:"country"`
	City            string `json:"city"`
	Street          string `json:"street"`
}

type Student struct {
	SID            int64          `json:"s_id"`
	UserName       string         `json:"user_name"`
	HashedPassword string         `json:"hashed_password"`
	FullName       string         `json:"full_name"`
	Email          string         `json:"email"`
	Description    sql.NullString `json:"description"`
	Avatar         sql.NullString `json:"avatar"`
	UID            int64          `json:"u_id"`
	Credit         int32          `json:"credit"`
}

type StudentCourse struct {
	SID int64 `json:"s_id"`
	CID int64 `json:"c_id"`
}

type Subscription struct {
	SubID         int64  `json:"sub_id"`
	SID           int64  `json:"s_id"`
	PlanType      string `json:"plan_type"`
	SubExpireTime string `json:"sub_expire_time"`
	SubStartTime  string `json:"sub_start_time"`
}

type University struct {
	UID            int64  `json:"u_id"`
	UniversityName string `json:"university_name"`
	Abbreviation   string `json:"abbreviation"`
	EmailExtension string `json:"email_extension"`
	Country        string `json:"country"`
	City           string `json:"city"`
	Street         string `json:"street"`
}
