DROP TABLE IF EXISTS Subscription;
DROP TABLE IF EXISTS Mentor;
DROP TABLE IF EXISTS Student_Courses;
DROP TABLE IF EXISTS Course;
DROP TABLE IF EXISTS Student;
DROP TABLE IF EXISTS University;
DROP TABLE IF EXISTS Addresses;